#관리자 권한 갖기
sudo: required
# 언어 (플랫폼)
language: generic

# 도커환경 구성.
service:
    -docker
#실행 전 설치
before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t hwchoi/docker-react-app -f Dockerfile.dev .

#실행할 스크립트 (테스트)
script:
    - docker run -e CI=true hwchoi/docker-react-app npm run test -- --coverage

#테스트 성공 후 할일
after_success:
    - echo "test success"

#AWS 연동을 위한 부분
deploy:
    # 실제 aws 배보 되는 서비스
    provider: elasticbeanstalk
    # 리전
    region: "ap-northeast-2"
    # 어플리케이션 이름
    app: "docker-react-app"
    # EB 환경 이름
    env: "DockerReactApp-env"
    # EB와 연동된 S3의 이름
    bucket_name: "elasticbeanstalk-ap-northeast-2-844556818888"
    # EB와 연동된 S3의 path
    bucket_path: "docker-react-app"
    # trigger Action이 올라올 github branch
    on:
        branch: main
    #AWS access key & Secret key (travis-ci web dashboard - settings 에 설정)
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY