FROM node:alpine

WORKDIR /usr/src/app

#소스 변경 시 종속 라이브러리를 다시 설치해야하는 작업을 방지
#처음 라이브러리 설치 시 라이브러리가 캐싱되어 있다.
COPY package.json ./

RUN npm install

#프로젝트파일을 컨테이너에 복사
COPY ./ ./

CMD ["npm", "run", "start"]